### ISSUE TITLE
[StarlinePlatform] Checking failed

### ISSUE THREAD

**Issue by DedMsk** [abdusalamov/homebridge-starline#3]
Перестал работать :-(

При попытке войти на сайт старлайна пишет - Обнаружена подозрительная активность.
Прохожу проверку с капчей и захожу в кабинет. Но в бридже все равно тишина

**Comment by abdusalamov** [comment]
@DedMsk Попробуй обновить пакет до версии 1.1.2. 
3 дня назад мы решили эту проблему и выпустили обновление.

**Comment by DedMsk** [comment]
> @DedMsk Попробуй обновить пакет до версии 1.1.2.
> 3 дня назад мы решили эту проблему и выпустили обновление.

Только что обновил плагин, зашел с ЛС с капчей и крыжыком Оставаться в системе, заработало. Из кабинета не выходил ) закрыл окно

**Comment by abdusalamov** [comment]
Да, они периодически локают за частые попытки входа (при рестарте хомбриджа), и разлокать можно только когда войдешь на сайте с капчей. Все соединения сразу начинают считаться валидными :)

**Comment by DedMsk** [comment]
А технически возможно в плагине автоматизировать типа входа на сайт и подтверждения капчи ? ) Когда возникает подозрительная активность )

**Comment by abdusalamov** [comment]
Ну это надо разгадывать капчу. Не знаю пока кого интегрировать для этого. Но в любом случае, такая подозрительная активность случается чаще всего при частых рестартах хомбриджа. У кого хомбридж работает неделями, проблем не возникает. Не знаю пока стоит ли решать такую проблему. 

Если всем покажется неудобным, всегда можно переехать на взрослое апи. Ключи для апи старлайн выдает каждому клиенту при запросе в поддержку.

**Comment by FreeSl-ru** [comment]
Поставил плагин версии 1.1.2 
ошибки : [StarlinePlatform] Checking failed
имя и пароль правильные.
плагин ещё рабочий?

**Comment by FreeSl-ru** [comment]
один раз проскочило такое:
[12/6/2019, 7:36:00 AM] [StarlinePlatform] Checking failed
[12/6/2019, 7:36:02 AM] [Config] Starting terminal session
[12/6/2019, 7:36:04 AM] [StarlinePlatform] Checking failed
[12/6/2019, 7:36:05 AM] [Config] Terminal session ended.
[12/6/2019, 7:36:08 AM] [StarlinePlatform] Checking failed
