### ISSUE TITLE
[StarlinePlatform] Checking failed 

### ISSUE THREAD

**Issue by FreeSl-ru** [abdusalamov/homebridge-starline#5]
Поставил плагин версии 1.1.2
ошибки : [StarlinePlatform] Checking failed
имя и пароль правильные, на сайт заходит без проблем.
плагин ещё рабочий?

один раз проскочило такое:
[12/6/2019, 7:36:00 AM] [StarlinePlatform] Checking failed
[12/6/2019, 7:36:02 AM] [Config] Starting terminal session
[12/6/2019, 7:36:04 AM] [StarlinePlatform] Checking failed
[12/6/2019, 7:36:05 AM] [Config] Terminal session ended.
[12/6/2019, 7:36:08 AM] [StarlinePlatform] Checking failed

**Comment by Ufocultist** [comment]
Добрый день.
Тоже стоит 1.1.2 и такая же ошибка.
На сайт захожу, имя машины соответсвует имени в конфиге, логин и пароль тоже проверял.
В логе:
homebridge[6572]: [Wed Dec 11 2019 10:12:41 GMT+0400 (+04)] [StarlinePlatform] Checking failed
Похоже со стороны старлайна "прикрыли лавочку".

**Comment by aptyp222** [comment]
такая же херня

**Comment by manamaser** [comment]
Аналогично

**Comment by deveaf** [comment]
похоже ждать уже нечего (

**Comment by abdusalamov** [comment]
Ребята, в телеграм-чате https://t.me/homebridge_starline сообщали, что для тестирования и разработки нужен кто-нибудь, кто сможет поделиться логином-паролем, потому что один аккаунт, на котором мы тестировали, больше не обслуживается (сигналка отключена у владельца). 

Пишите туда, если есть желающие помочь. Проверять не на чем.

**Comment by abdusalamov** [comment]
@FreeSl-ru @Ufocultist @aptyp222 @manamaser @deveaf Попробуйте обновиться до 1.1.3
